class LogoKiller{
	public static void main(String[] values ){
		System.out.println("Invoking main LogoKiller");
		Logo logo=new Logo();
		System.out.println("Logo name:"+logo.name);
		System.out.println("Logo filesize:"+logo.filesize);
		System.out.println("Logo length:"+logo.length);
		System.out.println("Logo design:"+logo.design);
		System.out.println("Logo color:"+logo.color);
		System.out.println("Logo color1:"+logo.color1);
		System.out.println("Logo fontSize :"+logo.fontsize);
		System.out.println("Logo width:"+logo.width);
		System.out.println("Logo type :"+logo.type);
		System.out.println("Logo source:"+logo.source);
		System.out.println("================================================================");
		Logo logo1=new Logo("Google");
		System.out.println("Logo name:"+logo1.name);
		System.out.println("================================================================");
		Logo logo2=new Logo("Google","Kunal sen");
		System.out.println("Logo name:"+logo2.name);
		System.out.println("Logo source:"+logo2.source);
		System.out.println("================================================================");
		Logo logo3=new Logo("Domino's Pizza","Wikimedia Commons",200);
		System.out.println("Logo name:"+logo3.name);
		System.out.println("Logo filesize:"+logo3.filesize);
		System.out.println("Logo source:"+logo3.source);
		System.out.println("================================================================");
		Logo logo4=new Logo("Domino's Pizza","Wikimedia Commons",200,5.0f);
		System.out.println("Logo name:"+logo4.name);
		System.out.println("Logo source:"+logo4.source);
		System.out.println("Logo filesize:"+logo4.filesize);
		System.out.println("Logo length:"+logo4.length);
		System.out.println("================================================================");
		Logo logo5=new Logo("Domino's Pizza","Wikimedia Commons",200,5.0f,"Graphic");
		System.out.println("Logo name:"+logo5.name);
		System.out.println("Logo source:"+logo5.source);
		System.out.println("Logo filesize:"+logo5.filesize);
		System.out.println("Logo length:"+logo5.length);
		System.out.println("Logo design:"+logo5.design);
		System.out.println("================================================================");
		Logo logo6=new Logo("Domino's Pizza","Wikimedia Commons",200,5.0f,"Graphic","Red");
		System.out.println("Logo name:"+logo6.name);
		System.out.println("Logo source:"+logo6.source);
		System.out.println("Logo filesize:"+logo6.filesize);
		System.out.println("Logo length:"+logo6.length);
		System.out.println("Logo design:"+logo6.design);
		System.out.println("Logo color:"+logo6.color);
		System.out.println("================================================================");
		Logo logo7=new Logo("Domino's Pizza","Wikimedia Commons",200,5.0f,"Graphic","Red","Blue");
		System.out.println("Logo name:"+logo7.name);
		System.out.println("Logo source:"+logo7.source);
		System.out.println("Logo filesize:"+logo7.filesize);
		System.out.println("Logo length:"+logo7.length);
		System.out.println("Logo design:"+logo7.design);
		System.out.println("Logo color:"+logo7.color);
		System.out.println("Logo color1:"+logo7.color1);
		System.out.println("================================================================");
		Logo logo8=new Logo("Domino's Pizza","Wikimedia Commons",200,5.0f,"Graphic","Red","Blue",14);
		System.out.println("Logo name:"+logo8.name);
		System.out.println("Logo source:"+logo8.source);
		System.out.println("Logo filesize:"+logo8.filesize);
		System.out.println("Logo length:"+logo8.length);
		System.out.println("Logo design:"+logo8.design);
		System.out.println("Logo color:"+logo8.color);
		System.out.println("Logo color1:"+logo8.color1);
		System.out.println("Logo fontSize :"+logo8.fontsize);
		System.out.println("================================================================");
		Logo logo9=new Logo("Domino's Pizza","Wikimedia Commons",200,5.0f,"Graphic","Red","Blue",14,7.0f);
		System.out.println("Logo name:"+logo9.name);
		System.out.println("Logo source:"+logo9.source);
		System.out.println("Logo filesize:"+logo9.filesize);
		System.out.println("Logo length:"+logo9.length);
		System.out.println("Logo design:"+logo9.design);
		System.out.println("Logo color:"+logo9.color);
		System.out.println("Logo color1:"+logo9.color1);
		System.out.println("Logo fontSize :"+logo9.fontsize);
		System.out.println("Logo width:"+logo9.width);
		System.out.println("================================================================");
		Logo logo10=new Logo("Domino's Pizza","Wikimedia Commons",200,5.0f,"Graphic","Red","Blue",14,7.0f,"Dynamic");
		System.out.println("Logo name:"+logo10.name);
		System.out.println("Logo source:"+logo10.source);
		System.out.println("Logo filesize:"+logo10.filesize);
		System.out.println("Logo length:"+logo10.length);
		System.out.println("Logo design:"+logo10.design);
		System.out.println("Logo color:"+logo10.color);
		System.out.println("Logo color1:"+logo10.color1);
		System.out.println("Logo fontSize :"+logo10.fontsize);
		System.out.println("Logo width:"+logo10.width);
		System.out.println("Logo type :"+logo10.type);
		System.out.println("================================================================");
	}
}